/*
** Please edit this file as needed **
It's been generated by Zapatos as a custom type definition placeholder, and won't be overwritten
*/

import { AdminPermissions } from '$lib/schema/core/admin';

declare module 'zapatos/custom' {
	import type * as db from 'zapatos/db';
	export type PgAdmin_permissions = AdminPermissions; //['all']
}
