/*
** Please edit this file as needed **
It's been generated by Zapatos as a custom type definition placeholder, and won't be overwritten
*/
import { Actions } from '$lib/schema/communications/actions/actions';
declare module 'zapatos/custom' {
	import type * as db from 'zapatos/db';
	export type PgCommunication_actions = Actions; // replace with your custom type or interface as desired
}
