/*
** Please edit this file as needed **
It's been generated by Zapatos as a custom type definition placeholder, and won't be overwritten
*/
import type { CustomCode } from '$lib/schema/globals';

declare module 'zapatos/custom' {
	import type * as db from 'zapatos/db';
	export type PgCustom_code = CustomCode; // replace with your custom type or interface as desired
}
