/*
** Please edit this file as needed **
It's been generated by Zapatos as a custom type definition placeholder, and won't be overwritten
*/
import type { EmailMessage } from '$lib/schema/valibot';
declare module 'zapatos/custom' {
	import type * as db from 'zapatos/db';
	export type PgEmail_message = EmailMessage; // replace with your custom type or interface as desired
}
