/*
** Please edit this file as needed **
It's been generated by Zapatos as a custom type definition placeholder, and won't be overwritten
*/

import type { FunctionStepArray } from '$lib/schema/core/functions/steps';

declare module 'zapatos/custom' {
	import type * as db from 'zapatos/db';
	export type PgFunction_steps = FunctionStepArray; // replace with your custom type or interface as desired
}
