/*
** Please edit this file as needed **
It's been generated by Zapatos as a custom type definition placeholder, and won't be overwritten
*/
import type { Geometry } from '$lib/schema/globals';
declare module 'zapatos/custom' {
	export type PgGeometry = Geometry; // replace with your custom type or interface as desired
}
