/*
** Please edit this file as needed **
It's been generated by Zapatos as a custom type definition placeholder, and won't be overwritten
*/
import { Secrets } from '$lib/schema/core/instance';
declare module 'zapatos/custom' {
	import type * as db from 'zapatos/db';
	export type PgInstance_secrets = Secrets; // replace with your custom type or interface as desired
}
