/*
** Please edit this file as needed **
It's been generated by Zapatos as a custom type definition placeholder, and won't be overwritten
*/
import { type Message } from '$lib/schema/communications/whatsapp/webhooks/messages';
import { type WhatsappInboundMessageReceived } from '$lib/schema/communications/whatsapp/webhooks/ycloud';
declare module 'zapatos/custom' {
	import type * as db from 'zapatos/db';
	export type PgIncoming_whatsapp_message =
		| Message
		| WhatsappInboundMessageReceived['whatsappInboundMessage']; // replace with your custom type or interface as desired
}
