/*
** Please edit this file as needed **
It's been generated by Zapatos as a custom type definition placeholder, and won't be overwritten
*/
import type { Settings } from '$lib/schema/core/instance';

declare module 'zapatos/custom' {
	import type * as db from 'zapatos/db';
	export type PgInstance_settings = Settings; // replace with your custom type or interface as desired
}
