/*
** Please edit this file as needed **
It's been generated by Zapatos as a custom type definition placeholder, and won't be overwritten
*/
import type { PhoneNumber } from '$lib/schema/people/channels/channels';

declare module 'zapatos/custom' {
	import type * as db from 'zapatos/db';
	export type PgPhone_number = PhoneNumber; // replace with your custom type or interface as desired
}
