/*
** Please edit this file as needed **
It's been generated by Zapatos as a custom type definition placeholder, and won't be overwritten
*/
import { type SendDetail } from '$lib/schema/communications/email/sent_emails';
declare module 'zapatos/custom' {
	import type * as db from 'zapatos/db';
	export type PgSent_email_details = SendDetail; // replace with your custom type or interface as desired
}
