/*
** Please edit this file as needed **
It's been generated by Zapatos as a custom type definition placeholder, and won't be overwritten
*/

import type { ValidationArray } from '$lib/schema/people/custom_fields/validation';

declare module 'zapatos/custom' {
	import type * as db from 'zapatos/db';
	export type PgValidation_rules = ValidationArray; // replace with your custom type or interface as desired
}
