/*
** Please edit this file as needed **
It's been generated by Zapatos as a custom type definition placeholder, and won't be overwritten
*/
import { type Template } from '$lib/schema/communications/whatsapp/elements/template';

declare module 'zapatos/custom' {
	import type * as db from 'zapatos/db';
	export type PgWhatsapp_template = Template; // replace with your custom type or interface as desired
}
