/*
** Please edit this file as needed **
It's been generated by Zapatos as a custom type definition placeholder, and won't be overwritten
*/
import type { Message } from '$lib/schema/communications/whatsapp/elements/message';

declare module 'zapatos/custom' {
	import type * as db from 'zapatos/db';
	export type PgWhatsapp_message = Message; // replace with your custom type or interface as desired
}
